'use strict';
const nav=document.getElementById('chapters'),article=document.getElementById('content');
nav.innerHTML=chapters.map(([id,label],i)=>`<a href="#${id}" data-page="${id}"><small>${String(i+1).padStart(2,'0')}</small>${label}</a>`).join('');
function render(){const requested=location.hash.slice(1)||'overview';const id=pages[requested]?requested:'overview';const index=chapters.findIndex(c=>c[0]===id);article.innerHTML=pages[id]()+`<div class="next">${index?`<a href="#${chapters[index-1][0]}">← ${chapters[index-1][1]}</a>`:'<span></span>'}${index<chapters.length-1?`<a href="#${chapters[index+1][0]}">${chapters[index+1][1]} →</a>`:'<a href="#overview">返回全局图景 ↑</a>'}</div>`;document.title=chapters[index][1]+' · Solver Sculpt 图解';nav.querySelectorAll('a').forEach(a=>{a.classList.toggle('active',a.dataset.page===id);a.setAttribute('aria-current',a.dataset.page===id?'page':'false');});if(typeof setupInteractive==='function')setupInteractive(id);document.querySelectorAll('.copy').forEach(b=>b.onclick=async()=>{try{await navigator.clipboard.writeText(b.closest('.codebox').querySelector('code').textContent);b.textContent='已复制';}catch{b.textContent='请选中文本复制';}});}
window.addEventListener('hashchange',()=>{render();if(window.scrollY>240)article.scrollIntoView({block:'start'});article.focus({preventScroll:true});});
document.querySelector(".skip").onclick=e=>{e.preventDefault();article.focus();article.scrollIntoView({block:"start"});};
function setupInteractive(id){
 if(id==='hierarchy'){
  const choose=i=>{const d=levelData[i];document.querySelectorAll('[data-level]').forEach(b=>b.setAttribute('aria-pressed',Number(b.dataset.level)===i));document.getElementById('level-detail').innerHTML=`<h3>L${i} · ${d.title}</h3><p>${d.intro}</p><div class="tokens">${d.tokens.map(x=>`<span class="token">${x}</span>`).join('')}</div>${i===2?`<div class="weno-paths" aria-label="WENO 三条模板计算路径">${[0,1,2].map(k=>`<div class="weno-row"><div class="stencil">${[-2,-1,0,1,2].map((offset,j)=>`<span class="cell ${j>=k&&j<=k+2?'hot':''}">i${offset>0?'+'+offset:offset===0?'':offset}</span>`).join('')}</div><span aria-hidden="true">→</span><span class="token">q<sub>${k}</sub> · ω<sub>${k}</sub></span></div>`).join('')}<div class="center-label">三条路径求和 → 同一个 face trace</div></div>`:''}<div class="equation">${d.formula.replaceAll('\n','<br>')}</div><p class="small"><strong>${d.ports}</strong></p><p class="caption">${d.next}</p>`;};document.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>choose(Number(b.dataset.level)));choose(1);
 }
 if(id==='equations'){
 const models={burgers:['u','f(u) = u² / 2','a = |u|','标量非线性波；解析熵解用于 Burgers 数据。'],euler:['[ρ, ρv, E]','F = [ρv, ρv²+p, v(E+p)]','a = |v| + √(γp/ρ)','p=(γ−1)(E−ρv²/2)；密度与压力必须可容许。'],shallow:['[h, hv]','F = [hv, hv²+½gh²]','a = |v| + √(gh)','干态通量与水深保护必须按实现处理；有地形时需要额外平衡结构。']};const sel=document.getElementById('equation-select');const update=()=>{const m=models[sel.value];document.getElementById('physics-panel').innerHTML=`<div class="equation">state = ${m[0]}<br>${m[1]}<br>${m[2]}</div><p class="small">${m[3]}</p>`;};sel.onchange=update;update();
 }
 if(id==='supernet'){
 const detail=document.getElementById('mixture-detail');const choose=i=>{document.querySelectorAll('[data-mixture]').forEach(b=>b.setAttribute('aria-pressed',Number(b.dataset.mixture)===i));detail.innerHTML=i===1?table(['L1 插槽','候选模块'],[['Reconstruction','PC / minmod / MC / vanLeer / superbee / WENO3-JS / WENO5-JS / WENO5-Z / MP5 / TENO5 / MUSCL θ / unlimited MUSCL / linear5 / ENO3 / PPM / learned θ'],['Flux','Godunov / LLF / EO / frozen LLF / HLL / entropy-stable / stage-global LLF / learned LLF'],['Time','Euler / SSPRK2 / SSPRK3']]):table(['L2 搜索位置','候选机制'],[['Reconstruction family','PC / TVD / WENO3 / WENO5 / MP5'],['TVD slope','minmod / MC / vanLeer / superbee'],['WENO5 weights','JS / Z / TENO / linear / learned-ε Z；每套先归一化，再共享 gate 混合'],['MP5 limiter','Identity / MP5 limiter；作用于同一个五阶预测'],['Flux family','dissipative center / Godunov / EO'],['Central flux / speed','arithmetic / entropy-conservative；local / frozen / stage-global / learned LLF'],['Time（仍为 L1）','Euler / SSPRK2 / SSPRK3']]);};document.querySelectorAll('[data-mixture]').forEach(b=>b.onclick=()=>choose(Number(b.dataset.mixture)));choose(1);
 const update=()=>{const logits=[0,1,2].map(i=>Number(document.getElementById('logit-'+i).value));const rho=[0,1,2].map(i=>Number(document.getElementById('rho-'+i).value));const base=logits.map(v=>Math.exp(v-Math.max(...logits)));const gates=rho.map(v=>Math.max(0,Math.min(1,1.2/(1+Math.exp(-v))-.1)));let raw=base.map((v,i)=>v*gates[i]);const fallback=raw.reduce((a,b)=>a+b,0)===0;if(fallback)raw=base;const sum=raw.reduce((a,b)=>a+b,0),weights=raw.map(v=>v/sum);weights.forEach((w,i)=>{document.getElementById('weight-'+i).textContent=(w*100).toFixed(1)+'%';document.getElementById('bar-'+i).style.width=w*100+'%';document.getElementById('logit-value-'+i).textContent=logits[i].toFixed(1);document.getElementById('rho-value-'+i).textContent=rho[i].toFixed(1);});const best=weights.indexOf(Math.max(...weights));document.getElementById('gate-result').textContent=(fallback?'所有 gate 关闭 → 回到 softmax。':'软输出 = '+weights.map((w,i)=>w.toFixed(3)+' × '+['PC','MC','WENO5-JS'][i]).join(' + ')+'。')+' 硬导出 → '+['PC','MUSCL MC','WENO5-JS'][best]+'；需重新验证误差与成本。';};document.querySelectorAll('.expert input').forEach(x=>x.oninput=update);document.getElementById('reset-gates').onclick=()=>{[0,1,2].forEach(i=>{document.getElementById('logit-'+i).value=[-1,0,2][i];document.getElementById('rho-'+i).value=2;});update();};update();
 }
 if(id==='budget'){
 const candidates=[{name:'Checkpoint A',cost:70,error:.030},{name:'Checkpoint B',cost:120,error:.014},{name:'Checkpoint C',cost:180,error:.010}];const slider=document.getElementById('budget-slider');const update=()=>{const budget=Number(slider.value);document.getElementById('budget-value').textContent=budget;const eligible=candidates.filter(x=>x.cost<=budget);const best=eligible.length?eligible.reduce((a,b)=>a.error<b.error?a:b):null;document.getElementById('budget-results').innerHTML=`<div class="budget-bars">${candidates.map(c=>`<div class="budget-row"><span>${c.name}<br><span class="muted">NMSE ${c.error.toFixed(3)}</span></span><div class="budget-track"><i class="${c.cost<=budget?'ok':'bad'}" style="width:${c.cost/2}%"></i></div><span>${c.cost} <span class="badge ${c.cost<=budget?'':'bad'}">${c.cost<=budget?'合格':'超标'}</span></span></div>`).join('')}</div><div class="result-strip">${best?'选择 '+best.name+'：预算内误差最低。':'没有预算可行的 checkpoint；报告不可行，不自动放宽预算。'}</div>`;};slider.oninput=update;update();
 }
 if(id==='quickstart'){
 const select=document.getElementById('config-level');const update=()=>{const cfg={...budgetConfig,mixture_level:Number(select.value)},text=JSON.stringify(cfg,null,2);document.getElementById('config-code').innerHTML=code('JSON · search-config.json',text);document.getElementById('download-config').href='data:application/json;charset=utf-8,'+encodeURIComponent(text+'\n');const b=document.querySelector('#config-code .copy');b.onclick=async()=>{try{await navigator.clipboard.writeText(text);b.textContent='已复制';}catch{b.textContent='请选中文本复制';}};};select.onchange=update;update();
 }
}
// Bind interactive chapters when opening a deep link on first load.
render();
